"""add authentication fields to users

Revision ID: 4858bd052844
Revises: 6622f1ff07bd
Create Date: 2026-09-24 18:39:54.063345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4858bd052844"
down_revision: Union[str, Sequence[str], None] = "6622f1ff07bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        # Valor vacío para las filas existentes: nunca coincide con un hash válido,
        # así que esos usuarios no pueden iniciar sesión hasta que se les asigne una contraseña.
        batch_op.add_column(
            sa.Column("hashed_password", sa.String(), server_default="", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("hashed_password")

    # ### end Alembic commands ###
